### ISSUE TITLE
Including two different vendor autoload files both with Kint causes fatal error

### ISSUE THREAD

**Issue by amcsi** [kint-php/kint#110]
Fatal error: Cannot redeclare kintLite() (previously declared in path\to\vendor\raveren\kint\Kint.class.php:619) in other\path\to\vendor\raveren\kint\Kint.class.php on line 740

This is due to `Kint.class.php` being among the autoload files, and a function definition being there with no `function_exists()` check.

May I suggest you wrap the definition of `kintLite()` in a `function_exists()` condition?

**Comment by raveren** [comment]
I pushed the ad-hoc solution to master, please check if it's working now.

The wip branch

https://github.com/raveren/kint/tree/1.0.0-wip

no longer uses the stupid function so it's solved there.

**Comment by amcsi** [comment]
I updated both Kints.

I am now getting:

Notice: Constant KINT_DIR already defined in other\path\to\vendor\raveren\kint\Kint.class.php on line 7

Fatal error: Cannot redeclare class kintParser in path\to\vendor\raveren\kint\parsers\parser.class.php on line 448

(it was line 556 when I was trying dev-1.0.0-wip on both)

**Comment by raveren** [comment]
what configuration are you on? How come you need two kints?

**Comment by amcsi** [comment]
I have an API project folder that uses Kint.
I also have an MVC project in a completely different directory that uses Kint that also uses the API by requiring its vendor/autoload.php file. Hence 2 Kints meet.

**Comment by raveren** [comment]
Wow, that's interesting :D

Mind I ask, what are the two projects that you're using :)

I made a fix in a new branch cause I can't test it out properly:

https://github.com/raveren/kint/tree/fix-110

could you switch both kint to that branch and report whether the fix worked and I'll merge it to master and WIP

**Comment by amcsi** [comment]
You have successfully fixed the fatal error issue when including two different vendor autoloads with Kint.

However, an unrelated bug came up with this commit fix of yours, which happens regardless whether I include 1, or more vendor autoloads. It happens when I call `sd('lol')`:

Fatal error: Maximum function nesting level of '100' reached, aborting! in D:\z\home\amcsi\test\kinttest\kint2\vendor\composer\ClassLoader.php on line 268

Call Stack:
    0.0002     125384   1. {main}() D:\z\home\amcsi\test\kinttest\kint2\index.php:0
    0.0004     126704   2. include('D:\z\home\amcsi\test\kinttest\kint2\vendor\autoload.php') D:\z\home\amcsi\test\kinttest\kint2\index.php:2
    0.0008     136832   3. ComposerAutoloaderInit2887abbf74a21b146fc9e3adb2be7fab::getLoader() D:\z\home\amcsi\test\kinttest\kint2\vendor\autoload.php:7
    0.0022     183032   4. composerRequire2887abbf74a21b146fc9e3adb2be7fab() D:\z\home\amcsi\test\kinttest\kint2\vendor\composer\autoload_real.php:48
    0.0025     184392   5. require('D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php') D:\z\home\amcsi\test\kinttest\kint2\vendor\composer\autoload_real.php:57
    0.0027     185584   6. require('D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php') D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php:4
    0.0028     186432   7. require('D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php') D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php:4
    0.0029     187280   8. require('D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php') D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php:4
    0.0030     188128   9. require('D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php') D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php:4
    0.0031     188976  10. require('D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php') D:\z\home\amcsi\test\kinttest\kint2\vendor\raveren\kint\Kint.class.php:4

(etc.)

**Comment by raveren** [comment]
goddamnit, try again, stupid mistake :)

**Comment by amcsi** [comment]
It works!

**Comment by raveren** [comment]
Alright. Would it work for you if I merged the patch into WIP branch only? I'm a little squeamish about updating the stable channel without testing.

Also, do you mind telling me what were the two projects? :)

**Comment by amcsi** [comment]
It's ok.

The projects are proprietary, but basically the API project is for doing something with the database, and the MVC project is one that is accessible through the CMS and interacts mostly with the API, mainly for writes.
The API is accessed mostly by the MVC project, but it can also be used optionally by any other subprojects in the CMS, mainly for reads.

**Comment by amcsi** [comment]
This has not been merged into master yet. This fix has not caused myself any problems to far, but lack of this fix still cause the issues in this issue.

**Comment by amcsi** [comment]
Please have this issue reopened. The fix has still not been merged into the main project.

**Comment by raveren** [comment]
Please tell me if it's working now

**Comment by amcsi** [comment]
I can confirm that this new commit solves the issue that can be found in the previous commit, d4780fc6e974f00c427c1fd2492dca4dcd636704
